# Generated by Django 4.1.6 on 2023-02-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_rename_studentid_msg_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='teacherName',
        ),
        migrations.AddField(
            model_name='msg',
            name='teacherId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
